# Site settings
title: Jason James Loughlin
email: jasonloughlin@yahoo.com
description: > # this means to ignore newlines until "baseurl:" Actor in New York City. Broadway Film and Television
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonjamesloughlin.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
